# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
# We edit the DeepSeek chat template to ensure (a) the reasoning block within <think> and </think> is included in the completion and (b) the <think> tag is not part of the prefill so that the format reward works
# dataset_name: /projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/pretrain_summaries/test/qwen72B_step_1_grpo_test_cleaned.csv
dataset_name: /projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/grpo/data_combined.csv
# dataset_name: /projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/grpo/data_etpr_cog_mci_park.csv
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>. Reply in English only, do not use other languages."

# GRPO trainer config
bf16: true
use_vllm: true
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-3B-combned-Open-R1-GRPO
hub_strategy: every_save
learning_rate: 1.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
optim : "adamw_torch"
lr_scheduler_type : "cosine"
max_prompt_length: 6000
max_completion_length: 3500
max_steps: -1
num_generations: 4
num_train_epochs: 1
# output_dir: data/Qwen2.5-3B-etpr-cog-mci-park-Open-R1-GRPO
overwrite_output_dir: true
# per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
hub_private_repo: true
report_to:
- wandb
reward_funcs:
- correctness
- format
- tag_count
reward_weights:
- 1.0
- 1.0
- 1.0
save_strategy: "steps"
save_total_limit: 100
save_steps : 100
output_dir : "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/open-r1/ckpt/qwen_3B_combined_lora"
seed: 42
temperature: 0.7
top_p: 0.95
warmup_ratio: 0.1
scale_rewards: true

# Lora parameters
use_peft: true
peft_type: LORA
lora_r: 64
lora_alpha: 64
lora_dropout : 0.1
bias: none
lora_target_modules:
  - up_proj
  - down_proj
  - gate_proj
  - k_proj
  - q_proj
  - v_proj
  - o_proj
inference_mode: false