# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: 
# - ../data/nacc/training_data/training_data_grpo/train_summary.csv
# - ../data/nacc/training_data/training_data_grpo/skywork_style/train_filtered.csv
# - ../data/nacc/training_data/training_data_grpo/stage_wise/stage_1.csv
# - ../data/nacc/training_data/training_data_grpo/stage_wise/stage_2.csv
# - ../data/nacc/training_data/training_data_grpo/stage_wise/stage_3.csv
# - ../data/nacc/training_data/training_data_grpo/stage_wise/stage_4.csv
- ../data/other_medical_datasets/medqa/clean/medqa_train.jsonl
# - ../data/nacc/training_data/training_data_grpo/subset/all_train_sub.csv
- ../data/nacc/training_data/training_data_grpo/subset/gs_8/train_filtered_sub.csv
# - ../data/nacc/training_data/training_data_grpo/subset/stage_wise_sub.csv
shuffle_dataset: false

system_prompt: "Please reason step by step, and put your final answer within \\boxed{}."

# GRPO trainer config
bf16: true
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.18
do_eval: false
gradient_accumulation_steps: 16
# steps_per_generation: 32
# gradient_accumulation_steps: 10
# steps_per_generation: 20
gradient_checkpointing: true
# gradient_checkpointing_kwargs:
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen25-3B-filtered-Open-R1-GRPO
hub_strategy: every_save
learning_rate: 1.0e-06
beta: 0.001
# beta: 0.0
# entropy_coeff: 0.00001
weight_decay: 0.01
# wandb_log_unique_prompts: true
optim : "adamw_torch"
lr_scheduler_type : "cosine"
max_prompt_length: 2000
max_completion_length: 2000
max_steps: -1
num_generations: 8
# num_iterations: 2
num_train_epochs: 1
# per_device_eval_batch_size: 2
per_device_train_batch_size: 1
push_to_hub: false
hub_private_repo: true
report_to:
- wandb
reward_funcs:
- correctness
# - majority_voting
# - hybrid
# - format
# - tag_count
reward_weights:
- 1.0
# - 1.0
# - 1.0
log_completions: false
log_level: info
logging_first_step: true
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_total_limit: 100
save_steps : 500
overwrite_output_dir: true
log_completions_local: true
output_dir : "ckpt_using_subset/qwen25_3B_drgrpo_gp8_medqa_train_filtered_sub"
log_path: "logs_using_subset/train_completions/qwen25_3B_drgrpo_gp8_medqa_train_filtered_sub.csv"
seed: 42

temperature: 1.0
top_p: 1.0
min_p: 0

warmup_ratio: 0.1
scale_rewards: false
loss_type: dr_grpo
mask_truncated_completions: true
over_generation_factor: 1
train_type: grpo
use_liger_loss: false
use_liger_kernel: false

# data_split: true
# # eval_strategy: 'no'
# eval_strategy: "steps"
# eval_steps: 50
# load_best_model_at_end: true