
#%%
import os
import torch
import argparse
import pandas as pd
import torch.distributed as dist
import json
import warnings
import random
from vllm import LLM, SamplingParams
warnings.filterwarnings("ignore")

from tqdm import tqdm
from datetime import timedelta
from torch.nn.parallel import DistributedDataParallel as DDP
from transformers import AutoTokenizer, AutoModelForCausalLM
# os.environ['HF_HOME'] = '/projectnb/vkolagrp/skowshik/.cache/'
PREFIX = "./data"

#%%
def get_parser():
    parser = argparse.ArgumentParser(description="Summary Generation")
    parser.add_argument("--max_new_tokens", default=4096, type=int, help="maximum new tokens")
    parser.add_argument("--model_id", default="meta-llama/Meta-Llama-3-8B-Instruct", type=str, help="huggingface model name")
    parser.add_argument("--batch_size", default=4, type=int, help="Specify the batch size")
    parser.add_argument("--distributed", action="store_true", help="Set True for Distributed Training")

    return parser

#%%

def stop_token_list():
    """
    The stop token list for vLLM engine
    Note: You can add more stop tokens
    if you are using other LLMs that have stop tokens
    """
    stop_tokens = [
        "Question:",
    ]

    return stop_tokens
 
def get_summary_llama(llm, tokenizer, input_texts, device, args, system_msg):
    """This is a function to generate LLAMA summaries using vllm https://github.com/vllm-project/vllm

    Args:
        llm: LLM object
        tokenizer: Huggingface tokenizer
        input_texts (List): A list of input texts / prompts
        device (str): cuda or cpu
        system_msg (str): system message for the LLAMA prompt
        args: other arguments

    Returns:
        List: A list of generated responses
    """
    
    prompts = []
    responses = []
    
    messages = [
        [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": text},
        ] for text in input_texts
    ]
    
    for message in messages:
        input_ids = tokenizer.apply_chat_template(
            message,
            add_generation_prompt=True,
            tokenize=False,
            # return_tensors="pt"
        )
        
        prompts.append(input_ids)
        
    stop_tokens = stop_token_list()
    
    # https://github.com/vllm-project/vllm/blob/main/vllm/sampling_params.py#L38-L66
    sampling_params = SamplingParams(
        temperature=0.2,
        max_tokens=args.max_new_tokens,
        # stop=stop_tokens
    )
    
    completions = llm.generate(
        prompts=prompts,
        sampling_params=sampling_params,
    )
    
    for i, output in enumerate(completions):
        temp_gen = output.outputs[0].text
        responses.append(temp_gen)
        
    print('Successfully finished generating', len(prompts), 'samples!')
    
    return responses

def create_batches(dataframe, batch_size):
    """Yield successive n-sized batches from dataframe."""
    for i in range(0, len(dataframe), batch_size):
        yield dataframe.iloc[i:i + batch_size]
        
        
def main(args):
    device = torch.device("cuda")
    all_nacc = pd.read_csv(f"{PREFIX}/nacc_unique_with_summary.csv")
    print(f"Number of cases to process: {len(all_nacc)}")
    json_name = f"{PREFIX}/nacc_unique_with_llama_summaries_3/nacc_unique_with_llama_summaries_3.json"

    # diag_system_msg = "Using the patient and diagnosis information provided, your role is to function as a behavioral neurologist AI. Provide a diagnostic summary for the described patient, classifying their cognitive status as 'normal cognition,' 'mild cognitive impairment,' or 'dementia' from the diagnosis information. If any cognitive disorders are identified, include the primary, secondary etiological diagnosis and contributing factors for impairment along with the reasoning behind this conclusion. Incorporate evidence from MRI and PET images if available, but omit if not. Offer a conclusion based on your findings. Exclude patient history from your summary. Also include a statement in the end advising consultation with a specialist, as your responses are generated by an AI model. Do not print CDR. Make the ouput look pretty and organized."
    diag_system_msg = "You are a behavioral neurologist AI."

    patient_system_msg = "Using the information provided, please generate a complete and comprehensive patient medical history summary. Summarize the findings in the present tense, focusing on clear and concise language. Include all tests and the test results in the summary. Ensure the summary includes Subject Demographics, Subject Family History, Subject Medications, Subject Health History, Physical, HIS and CVD, UPDRS, Neuropsychiatric Inventory Questionnaire, Geriatric Depression Scale, Functional Assessment Scale, Physical/ Neurological Exam Findings, Neuropsychological battery Summary Scores, Mini-mental state examination score (MMSE), Montreal Cognitive Assessment score (MoCA), Genetic testing and imaging evidence. Do not include patient's name. Do not mention the term 'UDS'."
    
    labels = ["Alzheimer's disease", "Lewy body dementia", "Parkinson's disease", "Vascular dementia", "Prion disease", "Frontotemporal lobar degeneration", "Normal pressure hydrocephalus", "any psychiatric conditions", "traumatic brain injury", "Huntington's disease", "multiple systems atrophy", "delirium"]

    llm = LLM(
        model=args.model_id,
        tokenizer=args.model_id,
        dtype='bfloat16',
        tensor_parallel_size=n_devices,
        gpu_memory_utilization=0.90,
        enable_lora=False
    )
    
    tokenizer = AutoTokenizer.from_pretrained(args.model_id, padding_side='left')
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    
    print(json_name)
    
    for batch in tqdm(create_batches(all_nacc, args.batch_size)):
        diag_texts = batch['diag_SUMMARY'].tolist()
        patient_texts = batch['patient_SUMMARY'].tolist()
        # print(len(diag_texts))
        print("Generating patient prompts")
        patient_responses = get_summary_llama(llm, tokenizer, patient_texts, device, args, patient_system_msg)
        modified_diag_texts = []
        additional_diag_tests = []
        instructions = []
        for i, text in enumerate(diag_texts):
            new_input_diag = "Provide a cognitive diagnosis for a patient presenting with the following information. Exclude patient history from your summary. Patient: " + patient_responses[i] + "\n Diagnosis: " + diag_texts[i]
            modified_diag_texts.append(new_input_diag)

            label = random.choice(labels)
            instruction = f"Does this patient have {label}?"
            instructions.append(instruction)
            add_input_diag = f"{instruction}. Patient: " + patient_responses[i] + "\n Diagnosis: " + diag_texts[i]
            additional_diag_tests.append(add_input_diag)


        print("Generating diagnosis:")
        diag_responses = get_summary_llama(llm, tokenizer, modified_diag_texts, device, args, diag_system_msg)
        additional_diag_responses = get_summary_llama(llm, tokenizer, additional_diag_tests, device, args, diag_system_msg)
        
        for i, row in batch.iterrows():
            with open(json_name, 'a', encoding='utf-8') as json_file:
                summary_data = {
                    "index": row.name,
                    "NACCID": row["NACCID"],
                    "NACCVNUM": row["NACCVNUM"],
                    "NACCNMRI": row["NACCNMRI"],
                    "NACCMRSA": row["NACCMRSA"],
                    "NACCADC": row["NACCADC"],
                    "VISITMO": row["VISITMO"],
                    "VISITDAY": row["VISITDAY"],
                    "VISITYR": row["VISITYR"],
                    "NACCUDSD": row["NACCUDSD"],
                    "instruction": "Provide a cognitive diagnosis for a patient presenting with the following information.",
                    "patient_SUMMARY": row["patient_SUMMARY"],
                    "diag_SUMMARY": row["diag_SUMMARY"],
                    "patient_LLAMA_SUMMARY": patient_responses[i - batch.first_valid_index()],
                    "diag_LLAMA_SUMMARY": diag_responses[i - batch.first_valid_index()]
                }
                json_file.write(json.dumps(summary_data, ensure_ascii=False) + "\n")
                json_file.close()

            with open(json_name, 'a', encoding='utf-8') as json_file:
                summary_data = {
                    "index": row.name,
                    "NACCID": row["NACCID"],
                    "NACCVNUM": row["NACCVNUM"],
                    "NACCNMRI": row["NACCNMRI"],
                    "NACCMRSA": row["NACCMRSA"],
                    "NACCADC": row["NACCADC"],
                    "VISITMO": row["VISITMO"],
                    "VISITDAY": row["VISITDAY"],
                    "VISITYR": row["VISITYR"],
                    "NACCUDSD": row["NACCUDSD"],
                    "instruction": instructions[i - batch.first_valid_index()],
                    "patient_SUMMARY": row["patient_SUMMARY"],
                    "diag_SUMMARY": row["diag_SUMMARY"],
                    "patient_LLAMA_SUMMARY": patient_responses[i - batch.first_valid_index()],
                    "diag_LLAMA_SUMMARY": additional_diag_responses[i - batch.first_valid_index()]
                }
                json_file.write(json.dumps(summary_data, ensure_ascii=False) + "\n")
                json_file.close()
        torch.cuda.empty_cache()

#%%
if __name__ == "__main__":
    os.environ['HF_HOME'] = '/projectnb/vkolagrp/skowshik/.cache/'
    parser = get_parser()
    args = parser.parse_args()
    print(args.distributed)
    if args.distributed:
        n_devices = torch.cuda.device_count()
    else:
        n_devices = 1
    print(f"Using {n_devices} GPUs!")
    main(args)
