llm:
  # model_id: "Qwen/Qwen3-8B"
  model_id: "Qwen/Qwen3-32B"
  n_devices: 2
  max_model_len: 10000
  max_new_tokens: 100

data:
  test_data_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/test_summary.csv"
  test_data_summary_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/with_summary/test_np.csv"

# # ETPR
# models:
#   qwen25_3b: "../results_4/test_etpr/2025-05-24T164900_b271d4612335408d/test_etpr_output.jsonl"
#   qwen25_7b: "../results_4/test_etpr/2025-05-24T183519_a68ed6568f5b471d/test_etpr_output.jsonl"
#   qwen25_14b: "../results_4/test_etpr/2025-05-24T210316_2a2cc297abce4b37/test_etpr_output.jsonl"
#   qwen25_32b: "../results_4/test_etpr/2025-05-25T020718_9cf8d9eab3704d51/test_etpr_output.jsonl"
#   qwen3_4b: "../results_4/test_etpr/2025-05-25T095718_4e93b4dff6a849f2/test_etpr_output.jsonl"
#   # qwen25_3b_drgrpo: "../results_4/test_etpr/2025-05-25T135202_c7c79b179a8d4e7f/test_etpr_output.jsonl"
#   # qwen25_3b_drgrpo_no_KL: "../results_4/test_etpr/2025-05-26T060336_6638b4bed3ac4647/test_etpr_output.jsonl"
#   qwen25_3b_drgrpo_filtered: "../results_4/test_etpr/2025-06-01T170923_ce72472e04e24251/test_etpr_output.jsonl"
#   qwen25_3b_drgrpo_filtered_no_KL: "../results_4/test_etpr/2025-06-01T190816_4d67632741154754/test_etpr_output.jsonl"
#   # # qwen25_3b_drgrpo_filtered_entropy: "../results_4/test_etpr/2025-06-01T200110_e646601f416a4592/test_etpr_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_no_KL_hybrid: "../results_4/test_etpr/2025-06-05T063159_e8111ea29ed94f59/test_etpr_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_hybrid: "../results_4/test_etpr/2025-06-06T141829_e5ee2646c9da4d1c/test_etpr_output.jsonl"
#   # # qwen3b_drgrpo_filtered_cont: "../results_4/test_etpr/2025-06-08T035114_f6228aec6c294d40/test_etpr_output.jsonl"
#   # # qwen25_3B_drgrpo_filtered_hybrid_random_flip_all_0: "../results_4/test_etpr/2025-06-10T094325_2bed44d9bfaa4ff5/test_etpr_output.jsonl"
#   # qwen25_3B_drgrpo_filtered_oversample: "../results_4/test_etpr/2025-06-13T142008_65c31742a19441bd/test_etpr_output.jsonl"
#   qwen25_3B_drgrpo_filtered_oversample_3x: "../results_4/test_etpr/2025-06-19T092558_483127770b52430a/test_etpr_output.jsonl"
#   qwen25_3B_drgrpo_filtered_2_grad_updates: "../results_4/test_etpr/2025-06-20T102208_aed3191a94084c74/test_etpr_output.jsonl"
#   qwen25_3B_sft: "../results_4/test_etpr/2025-06-25T022639_eb6d3563bcb24971/test_etpr_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling: "../results_4/test_etpr/2025-06-26T195520_f7735a1d254c49b0/test_etpr_output.jsonl"
#   qwen25_3B_sft_with_eval: "../results_4/test_etpr/2025-06-26T233803_ee48cefcc71f46ba/test_etpr_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling_gp_16: "../results_4/test_etpr/2025-06-29T073533_3151af46b5654859/test_etpr_output.jsonl"

# ETPR
models:
  qwen25_3b: "../results/test_etpr/2025_07_10T155348_Qwen2.5_3B_Instruct/test_etpr_output.jsonl"
  qwen25_7b: "../results/test_etpr/2025_07_11T091118_Qwen2.5_7B_Instruct/test_etpr_output.jsonl"
  qwen25_14b: "../results/test_etpr/2025_07_12T155708_Qwen2.5_14B_Instruct/test_etpr_output.jsonl"
  qwen25_3B_drgrpo_gp16: "../results/test_etpr/2025_07_12T114509_qwen25_3B_drgrpo_gp16/test_etpr_output.jsonl"
  qwen25_3B_drgrpo_gp32: "../results/test_etpr/2025_07_15T103022_qwen25_3B_drgrpo_gp32/test_etpr_output.jsonl"
  qwen25_3B_sft: "../results/test_etpr/2025_07_15T203013_qwen25_3B_sft_with_eval/test_etpr_output.jsonl"


metrics:
  k: 1

output:
  result_dir: extracted_results
  plot_path: "outputs/full/etpr.pdf"

benchmark: "ETPR"
