

data:
  test_data_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/test_summary.csv"
  test_data_summary_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/with_summary/test_mci.csv"


# # MCI
# models:
#   qwen25_3b: "../results_4/test_mci/2025-06-07T172908_489aaa3ac0aa41cd/test_mci_output.jsonl"
#   qwen25_7b: "../results_4/test_mci/2025-06-07T173855_61ef77407cd5420f/test_mci_output.jsonl"
#   qwen25_14b: "../results_4/test_mci/2025-06-07T175143_5cf2a3faeabd4f9f/test_mci_output.jsonl"
#   qwen25_32b: "../results_4/test_mci/2025-06-07T182442_6b119a4048424ebf/test_mci_output.jsonl"
#   qwen3_4b: "../results_4/test_mci/2025-06-07T190405_ba01eeccdd6241c8/test_mci_output.jsonl"
#   qwen25_3b_drgrpo_filtered: "../results_4/test_mci/2025-06-07T193952_afd075d2c65f4d6a/test_mci_output.jsonl"
#   qwen25_3b_drgrpo_filtered_no_KL: "../results_4/test_mci/2025-06-07T195120_841fe23217cc449d/test_mci_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_no_KL_hybrid: "../results_4/test_mci/2025-06-07T195647_9b7f0fdf039c4d08/test_mci_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_hybrid: "../results_4/test_mci/2025-06-07T200518_ab1e47eb4d6e4207/test_mci_output.jsonl"
#   # # qwen3b_drgrpo_filtered_cont: "../results_4/test_mci/2025-06-08T061945_10a54c1aca174055/test_mci_output.jsonl"
#   # qwen25_3B_drgrpo_filtered_hybrid_random_flip_all_0: "../results_4/test_mci/2025-06-10T124826_ac43aa76ad154c6f/test_mci_output.jsonl"
#   # qwen25_3B_drgrpo_filtered_oversample: "../results_4/test_mci/2025-06-13T163622_90eb147d0b494cfd/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_filtered_oversample_3x: "../results_4/test_mci/2025-06-19T111639_eab65300e05d4537/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_filtered_2_grad_updates: "../results_4/test_mci/2025-06-20T122114_5ed9d734cad54ab4/test_mci_output.jsonl"
#   qwen25_3B_sft: "../results_4/test_mci/2025-06-25T032536_1d4e614664da4dec/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling: "../results_4/test_mci/2025-06-26T225406_27802182f9ff4c74/test_mci_output.jsonl"
#   qwen25_3B_sft_with_eval: "../results_4/test_mci/2025-06-27T003844_dbf17618ef504e14/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling_gp_16: "../results_4/test_mci/2025-06-29T111003_922a698a194a4511/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling_gp_32: "../results_4/test_mci/2025-06-30T105127_201db0f1b3974f68/test_mci_output.jsonl"

# MCI
# models:
#   qwen25_3b: "../results/test_mci/2025_07_11T084038_Qwen2.5_3B_Instruct/test_mci_output.jsonl"
#   qwen25_7b: "../results/test_mci/2025_07_12T090745_Qwen2.5_7B_Instruct/test_mci_output.jsonl"
#   qwen25_14b: "../results/test_mci/2025_07_12T230758_Qwen2.5_14B_Instruct/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_gp16: "../results/test_mci/2025_07_12T151453_qwen25_3B_drgrpo_gp16/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_gp32: "../results/test_mci/2025_07_15T141033_qwen25_3B_drgrpo_gp32/test_mci_output.jsonl"
#   qwen25_3B_sft: "../results/test_mci/2025_07_15T215529_qwen25_3B_sft_with_eval/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_gp16_stage_wise: "../results/test_mci/2025_07_18T132304_qwen25_3B_drgrpo_gp16_stage_wise/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_gp16_stage_wise_rewards: "../results/test_mci/2025_07_19T105751_qwen25_3B_drgrpo_gp16_stage_wise_rewards/test_mci_output.jsonl"
#   qwen25_3B_drgrpo_gp16_stages234_epoch2: "../results/test_mci/2025_07_21T133254_qwen25_3B_drgrpo_gp16_stages234_epoch2/test_mci_output.jsonl" 
#   qwen25_3B_drgrpo_gp16_filtered_step_1500: "../results/test_mci/2025_07_25T094642_qwen25_3B_drgrpo_gp16_filtered/test_mci_output.jsonl" 

models:
  qwen25_3B_old_prompt: "../results_sub/test_mci/2025_07_28T014352_Qwen2.5_3B_Instruct_old_prompt/test_mci_output.jsonl"
  qwen25_3B_drgrpo_gp16_all_train_sub_old_prompt: "../results_sub/test_mci/2025_07_28T022312_qwen25_3B_drgrpo_gp8_all_train_sub_old_prompt/test_mci_output.jsonl"
  qwen25_3B: "../results_sub/test_mci/2025_07_28T001626_Qwen2.5_3B_Instruct/test_mci_output.jsonl"
  qwen25_3B_drgrpo_gp16_all_train_sub: "../results_sub/test_mci/2025_07_28T010225_qwen25_3B_drgrpo_gp8_all_train_sub/test_mci_output.jsonl"
  qwen25_3B_drgrpo_gp16_all_train_sub_no_KL: "../results_sub/test_mci/2025_07_28T134458_qwen25_3B_drgrpo_gp8_all_train_sub_no_KL/test_mci_output.jsonl"
  qwen25_3B_drgrpo_gp16_train_filtered_sub: "../results_sub/test_mci/2025_08_04T114625_qwen25_3B_drgrpo_gp8_train_filtered_sub/test_mci_output.jsonl"
  qwen25_3B_drgrpo_gp16_train_filtered_sub_no_KL: "../results_sub/test_mci/2025_08_04T152855_qwen25_3B_drgrpo_gp8_train_filtered_sub_no_KL/test_mci_output.jsonl"
  qwen25_3B_drgrpo_gp16_stage_wise_sub: "../results_sub/test_mci/2025_08_04T114718_qwen25_3B_drgrpo_gp8_stage_wise_sub/test_mci_output.jsonl"
  qwen25_3B_drgrpo_gp16_stage_wise_sub_no_KL: "../results_sub/test_mci/2025_08_04T151132_qwen25_3B_drgrpo_gp8_stage_wise_sub_no_KL/test_mci_output.jsonl"

metrics:
  k: 1

output:
  result_dir: extracted_results_sub
  plot_path: "outputs_sub/full/mci.pdf"

benchmark: "MCI"
