llm:
  # model_id: "Qwen/Qwen3-8B"
  model_id: "Qwen/Qwen3-14B"
  n_devices: 2
  max_model_len: 10000
  max_new_tokens: 500


# NEUROPATH
models:
  qwen25_3B: "../train_results/nacc_train/2025_07_27T155316_Qwen2.5_3B_Instruct/nacc_train_output.jsonl"

output:
  result_dir: extracted_results_sub

benchmark: "Train"
