llm:
  # model_id: "Qwen/Qwen3-8B"
  model_id: "Qwen/Qwen3-32B"
  n_devices: 2
  max_model_len: 10000
  max_new_tokens: 500

data:
  test_data_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/test_summary.csv"
  test_data_summary_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/with_summary/test_np.csv"

# # NEUROPATH
# models:
#   qwen25_3b: "../results_4/test_np/2025-05-22T102606_e437f90d9d214379/test_np_output.jsonl"
#   qwen25_7b: "../results_4/test_np/2025-05-22T110515_2b125570ef924c24/test_np_output.jsonl"
#   qwen25_14b: "../results_4/test_np/2025-05-22T120010_dfcb71f07a7648bc/test_np_output.jsonl"
#   qwen25_32b: "../results_4/test_np/2025-05-22T140149_1e61b6d673c74246/test_np_output.jsonl"
#   qwen25_72b: "../results_4/test_np/2025-05-25T032216_477269aa42c94ed5/test_np_output.jsonl"
#   qwen3_4b: "../results_4/test_np/2025-05-22T192348_e628c7b6bf504593/test_np_output.jsonl"
#   qwen3_14b: "../results_4/test_np/2025-05-26T014758_0f6a1548a4a04c1f/test_np_output.jsonl"
#   qwen3_32b: "../results_4/test_np/2025-05-26T031125_7a5dc431d6ba4702/test_np_output.jsonl"
#   llama31_8b: "../results_4/test_np/2025-05-22T212141_45631bdbbb6748ab/test_np_output.jsonl"
#   # qwen25_3b_drgrpo: "../results_4/test_np/2025-05-23T153554_1c71e5f6fc5947d6/test_np_output.jsonl"
#   # qwen25_3b_drgrpo_no_KL: "../results_4/test_np/2025-05-26T013154_fadcfac71d954c1b/test_np_output.jsonl"
#   qwen25_3b_drgrpo_filtered: "../results_4/test_np/2025-06-01T150244_3c2a11c010b24e08/test_np_output.jsonl"
#   qwen25_3b_drgrpo_filtered_no_KL: "../results_4/test_np/2025-06-01T154608_8acf8fe2d7234c55/test_np_output.jsonl"
#   # # qwen25_3b_drgrpo_filtered_entropy: "../results_4/test_np/2025-06-01T160524_f804ff66499c4204/test_np_output.jsonl"
#   # # qwen25_3b_drgrpo_filtered_no_KL_hybrid: "../results_4/test_np/2025-06-04T130511_b12b60d071d4409b/test_np_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_no_KL_hybrid: "../results_4/test_np/2025-06-05T055502_5ff3ff78a47e4f68/test_np_output.jsonl"
#   # # qwen25_3b_drgrpo_filtered_no_KL_mu_2: "../results_4/test_np/2025-06-05T155103_74f117ac5d644d11/test_np_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_hybrid: "../results_4/test_np/2025-06-06T135241_78a17b4687094345/test_np_output.jsonl"
#   # # qwen3b_drgrpo_filtered_cont: "../results_4/test_np/2025-06-08T032144_22d97b29e8174ee6/test_np_output.jsonl"
#   # # qwen25_3B_drgrpo_filtered_hybrid_random_flip_all_0: "../results_4/test_np/2025-06-10T090238_dfbf585e1e7148ca/test_np_output.jsonl"
#   # qwen25_3B_drgrpo_filtered_oversample: "../results_4/test_np/2025-06-13T135351_63ff792f57594f0e/test_np_output.jsonl"
#   qwen25_3B_drgrpo_filtered_oversample_3x: "../results_4/test_np/2025-06-19T090455_c812f6e32c9c4cea/test_np_output.jsonl"
#   qwen25_3B_drgrpo_filtered_2_grad_updates: "../results_4/test_np/2025-06-20T095904_ffcb692e855b49ac/test_np_output.jsonl"
#   qwen25_3B_sft: "../results_4/test_np/2025-06-25T021606_298f1a97be7848bf/test_np_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling: "../results_4/test_np/2025-06-26T191618_709e96456c8d4575/test_np_output.jsonl"
#   qwen25_3B_sft_with_eval: "../results_4/test_np/2025-06-26T232710_15293079767c413a/test_np_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling_gp_16: "../results_4/test_np/2025-06-29T065418_54c7025152d84d67/test_np_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling_gp_32: "../results_4/test_np/2025-06-30T101522_ae81c28e31994698/test_np_output.jsonl"


# NEUROPATH
models:
  qwen25_3B: "../results/test_np/2025_07_13T162711_Qwen2.5_3B_Instruct/test_np_output.jsonl"
  qwen25_7B: "../results/test_np/2025_07_13T164130_Qwen2.5_7B_Instruct/test_np_output.jsonl"
  qwen25_14B: "../results/test_np/2025_07_13T172055_Qwen2.5_14B_Instruct/test_np_output.jsonl"
  qwen25_3B_drgrpo_gp16: "../results/test_np/2025_07_13T174802_qwen25_3B_drgrpo_gp16/test_np_output.jsonl"
  qwen25_3B_drgrpo_gp32: "../results/test_np/2025_07_15T101648_qwen25_3B_drgrpo_gp32/test_np_output.jsonl"
  qwen25_3B_sft: "../results/test_np/2025_07_15T202648_qwen25_3B_sft_with_eval/test_np_output.jsonl"
  

metrics:
  k: 1

output:
  result_dir: extracted_results
  plot_path: "outputs/full/neuropath.pdf"

benchmark: "Neuropath"
