

data:
  test_data_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/test_summary.csv"
  test_data_summary_path: "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/with_summary/test_np.csv"


# Cognitive status
# models:
#   qwen25_3b: "../results_4/test_cog/2025-06-06T183741_3e77c01ca0824916/test_cog_output.jsonl"
#   qwen25_7b: "../results_4/test_cog/2025-06-06T194543_557c837a5b5240b3/test_cog_output.jsonl"
#   qwen25_14b: "../results_4/test_cog/2025-06-06T211806_546da7bf3f4144ca/test_cog_output.jsonl"
#   qwen25_32b: "../results_4/test_cog/2025-06-06T235805_78176bf4718343cc/test_cog_output.jsonl"
#   qwen3_4b: "../results_4/test_cog/2025-06-07T110008_3ec9290398494186/test_cog_output.jsonl"
#   qwen25_3b_drgrpo_filtered: "../results_4/test_cog/2025-06-07T130227_606cf19a3c57477d/test_cog_output.jsonl"
#   qwen25_3b_drgrpo_filtered_no_KL: "../results_4/test_cog/2025-06-07T141131_dcbbc2e354e44ad8/test_cog_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_no_KL_hybrid: "../results_4/test_cog/2025-06-07T144613_b11d40b0082440d6/test_cog_output.jsonl"
#   # qwen25_3b_drgrpo_filtered_hybrid: "../results_4/test_cog/2025-06-07T154727_2cb7857d735b4a31/test_cog_output.jsonl"
#   # # qwen3b_drgrpo_filtered_cont: "../results_4/test_cog/2025-06-08T051259_9b1a3da50cab41d0/test_cog_output.jsonl"
#   # qwen25_3B_drgrpo_filtered_hybrid_random_flip_all_0: "../results_4/test_cog/2025-06-10T112544_4878530348a740b7/test_cog_output.jsonl"
#   # qwen25_3B_drgrpo_filtered_oversample: "../results_4/test_cog/2025-06-13T153611_59bfed197e944521/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_filtered_oversample_3x: "../results_4/test_cog/2025-06-19T102534_18086c75035540dc/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_filtered_2_grad_updates: "../results_4/test_cog/2025-06-20T112848_62b1cb57a78c4978/test_cog_output.jsonl"
#   qwen25_3B_sft: "../results_4/test_cog/2025-06-25T025851_3f891e25ea7a48a9/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling: "../results_4/test_cog/2025-06-26T211638_2bba98928cbf42a8/test_cog_output.jsonl"
#   qwen25_3B_sft_with_eval: "../results_4/test_cog/2025-06-27T001115_c490e82052db4174/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_filtered_option_shuffling_gp_16: "../results_4/test_cog/2025-06-29T093524_e7beb58f947e4ba9/test_cog_output.jsonl"


# Cognitive status
# models:
#   qwen25_3b: "../results/test_cog/2025_07_10T190058_Qwen2.5_3B_Instruct/test_cog_output.jsonl"
#   qwen25_7b: "../results/test_cog/2025_07_12T092616_Qwen2.5_7B_Instruct/test_cog_output.jsonl"
#   qwen25_14b: "../results/test_cog/2025_07_12T195109_Qwen2.5_14B_Instruct/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_gp16: "../results/test_cog/2025_07_12T133309_qwen25_3B_drgrpo_gp16/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_gp32: "../results/test_cog/2025_07_15T122746_qwen25_3B_drgrpo_gp32/test_cog_output.jsonl"
#   qwen25_3B_sft: "../results/test_cog/2025_07_15T213005_qwen25_3B_sft_with_eval/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_gp16_stage_wise: "../results/test_cog/2025_07_18T114940_qwen25_3B_drgrpo_gp16_stage_wise/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_gp16_stage_wise_rewards: "../results/test_cog/2025_07_19T093313_qwen25_3B_drgrpo_gp16_stage_wise_rewards/test_cog_output.jsonl"
#   qwen25_3B_drgrpo_gp16_stages234_epoch2: "../results/test_cog/2025_07_21T111309_qwen25_3B_drgrpo_gp16_stages234_epoch2/test_cog_output.jsonl" 

models:
  qwen25_3B_old_prompt: "../results_sub/test_cog/2025_07_28T140411_Qwen2.5_3B_Instruct_old_prompt/test_cog_output.jsonl"
  qwen25_3B_drgrpo_gp16_all_train_sub_old_prompt: "../results_sub/test_cog/2025_07_28T163134_qwen25_3B_drgrpo_gp8_all_train_sub_old_prompt/test_cog_output.jsonl"
  qwen25_3B: "../results_sub/test_cog/2025_07_28T091205_Qwen2.5_3B_Instruct/test_cog_output.jsonl"
  qwen25_3B_drgrpo_gp16_all_train_sub: "../results_sub/test_cog/2025_07_28T115650_qwen25_3B_drgrpo_gp8_all_train_sub/test_cog_output.jsonl"
  qwen25_3B_drgrpo_gp16_all_train_sub_no_KL: "../results_sub/test_cog/2025_07_28T141615_qwen25_3B_drgrpo_gp8_all_train_sub_no_KL/test_cog_output.jsonl"
  qwen25_3B_drgrpo_gp16_train_filtered_sub: "../results_sub/test_cog/2025_08_04T121246_qwen25_3B_drgrpo_gp8_train_filtered_sub/test_cog_output.jsonl"
  qwen25_3B_drgrpo_gp16_train_filtered_sub_no_KL: "../results_sub/test_cog/2025_08_04T155654_qwen25_3B_drgrpo_gp8_train_filtered_sub_no_KL/test_cog_output.jsonl"
  qwen25_3B_drgrpo_gp16_stage_wise_sub: "../results_sub/test_cog/2025_08_04T121210_qwen25_3B_drgrpo_gp8_stage_wise_sub/test_cog_output.jsonl"
  qwen25_3B_drgrpo_gp16_stage_wise_sub_no_KL: "../results_sub/test_cog/2025_08_04T153641_qwen25_3B_drgrpo_gp8_stage_wise_sub_no_KL/test_cog_output.jsonl"

  
metrics:
  k: 1

output:
  result_dir: extracted_results_sub
  plot_path: "outputs_sub/full/cogstat.pdf"

benchmark: "COGSTAT"
