# Model info
# C4AI Command-R 35B: CohereForAI/c4ai-command-r-v01
# Mistral 8x7B MoE 46B: mistralai/Mixtral-8x7B-Instruct-v0.1
# LLaMA 3 70B: meta-llama/Meta-Llama-3-70B-Instruct
# C4AI Command R+ 104B: CohereForAI/c4ai-command-r-plus
# Mistral 8x22B MoE 176B: mistralai/Mixtral-8x22B-Instruct-v0.1
model_name : "meta-llama/Meta-Llama-3-8B-Instruct"

# Dataset info
# English podcasts (7,359 episodes): shuyuej/English-Pretraining-Dataset
# Spanish podcasts (1,283 episodes): shuyuej/Spanish-Pretraining-Dataset
# French podcasts (569 episodes): shuyuej/French-Pretraining-Dataset
# Multilingual podcasts: shuyuej/Multilingual-Pretraining-Dataset
dataset_path : "./data/nacc_with_llama_summaries.json"

# This is my Hugging Face `read` and `write` tokens. Please replace it to yours.
# `read` token: for downloading models
# `write` token: for uploading your models to Hugging Face
# For your information: https://huggingface.co/settings/tokens
hf_read_token : "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"  # Hugging Face `read` Token
hf_write_token : "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"  # Hugging Face `write` Token

# LoRA
# LoRA attention dimension
lora_r : 16
# Alpha parameter for LoRA scaling
lora_alpha : 32
# Dropout probability for LoRA layers
lora_dropout : 0.1

# Saving path
result_dir : "./results"
save_dir : "./fine_tuned_v3"
data_save_dir : "./data"

# user, system, assistant
user : "patient_LLAMA_SUMMARY"
assistant : "diag_LLAMA_SUMMARY"
sysmsg : "Using the information provided, your task is to act as a behavioral neurologist and provide a diagnostic summary for the patient described. Ensure your summary clearly identifies the patient's cognitive status and outlines the primary etiological diagnosis, if any cognitive disorders are detected."

# Training length and number of the generated tokens
train_max_len : 2048
max_new_tokens : 1024

# Batch size
train_batch_size : 6

# Number of training epochs
epochs : 5

# Optimizer, Learning rate schedule, warm-up ratio
# paged_adamw_8bit, adamw_torch
optim : "paged_adamw_32bit"
lr_scheduler_type : "cosine"
warmup_ratio : 0.03

# activation checkpointing
# When enabled, a lot of memory can be freed at the cost of small decrease in the training speed
# due to recomputing parts of the graph during back-propagation.
gradient_checkpointing : True
# Number of update steps to accumulate the gradients
gradient_accumulation_steps : 1
# Initial learning rate
learning_rate : 0.0005
# Weight decay to apply to all layers except bias/LayerNorm weights
weight_decay : 0.01

# Save the model for a number of steps
save_strategy : "steps"
# Save the model and tokenizer every 100 steps
save_steps : 500
# Whether to save the optimizer and scheduler
save_only_model : True
# Number of total saved checkpoints
save_total_limit : 10

# Log every X updates steps
logging_steps : 1
# Logging save platform
log_save_platform : "wandb"

# Output directory where the model predictions and checkpoints will be stored
# Enable fp16/bf16 training (set bf16 to True with an A100)
# Whether to use fp16 16-bit (mixed) precision training instead of 32-bit training.
fp16 : False
# Whether to use bf16 16-bit (mixed) precision training instead of 32-bit training. Requires Ampere or higher
# NVIDIA architecture or using CPU (use_cpu) or Ascend NPU. This is an experimental API and it may change.
bf16 : True

# Pack multiple short examples in the same input sequence to increase efficiency
device_map : "auto"
# The number of GPUs for vLLM Engine
# https://docs.vllm.ai/en/latest/serving/distributed_serving.html
num_gpus_vllm : 4
gpu_utilization_vllm : 0.95