# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
# We edit the DeepSeek chat template to ensure (a) the reasoning block within <think> and </think> is included in the completion and (b) the <think> tag is not part of the prefill so that the format reward works
dataset_name: /projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/select_train_cases/train_selected.csv
# dataset_name: /projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/select_train_cases/all_incorrect.csv

# system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>, i.e., the reasoning process is enclosed within <think> </think> and the answer is enclosed within <answer> </answer> tags, respectively. Reply in English only, do not use other languages."

system_prompt: "You are a helpful AI assistant that provides well-reasoned and detailed responses. First, think through the reasoning process as an internal monologue, and then provide the user with the final answer. Respond using the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>, i.e., the reasoning process should be enclosed within <think>...</think> tags, and the final answer within <answer>...</answer> tags. Reply in English only, do not use other languages."

# GRPO trainer config
bf16: true
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.25
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
use_reentrant: false
# hub_model_id: Qwen2.5-7B-Open-R1-GRPO
# hub_strategy: every_save
learning_rate: 1.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
optim : "adamw_torch"
lr_scheduler_type : "cosine"
max_grad_norm: 0.2
max_prompt_length: 2000
max_completion_length: 2000
max_steps: -1
num_generations: 4
num_train_epochs: 1
output_dir: data/Qwen2.5-7B-Open-R1-GRPO
overwrite_output_dir: true
# per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: false
report_to:
- wandb
reward_funcs:
- correctness
- format
- tag_count
reward_weights:
- 1.0
- 1.0
- 1.0
save_strategy: "steps"
save_total_limit: 100
save_steps : 100
output_dir : "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/open-r1/ckpt/qwen25_7B_filtered"
seed: 42
temperature: 1.0
top_p: 1.0
warmup_ratio: 0.1
scale_rewards: false
loss_type: dr_grpo
