llm:
  # model_id: "Qwen/Qwen3-8B"
  model_id: "Qwen/Qwen3-14B" # LLM model used to extract answers
  n_devices: 2 # Number of GPUs to use
  max_model_len: 10000 # Max length of the model
  max_new_tokens: 500 # Max new tokens to generate

configs: # Config files for each benchmark
  config_np: "config/config_np.yml" # Neuropathology benchmark configuration
  config_mci: "config/config_mci.yml" # MCI benchmark configuration
  config_cog_stat: "config/config_cog_stat.yml" # Cognitive Status benchmark configuration
