# passed to vllm.LLM, you can use any accepted keyword argument
LLM:
  model: "Qwen/Qwen3-14B" # can be a path
  tensor_parallel_size: 2 # Number of GPUs used. Passed to vllm.LLM.tensor_parallel_size. 
  gpu_memory_utilization: 0.9 # Fraction of gpu memory reserved for model + attention
  max_model_len: 32000
  distributed_executor_backend: 'mp'
  seed: 1 # seed to initialize RNG for sampling
  enable_lora: false

# passed to vllm.SamplingParams, you can use any accepted keyword argument
sampling_params:
  n: 1 # Number of sequences to generate per prompt
  temperature: 0.7
  top_p: 0.8 # consider candidate tokens until the cumulative sum of their probabilities is top_p
  top_k: 20
  max_tokens: 5000 # maximum number of tokens to generate

prompt:
  system_prompt: "Please reason step by step, and put your final answer within \\boxed{}."