# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct 
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: 
- /projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/training_data_sft/train_summary.csv
dataset_num_proc: 40
shuffle_dataset: true

#SFT hyperparam
max_length: 4000
weight_decay: 0.0001
optim: adamw_torch
lr_scheduler_type: cosine
warmup_ratio: 0.1
learning_rate: 5.0e-05
gradient_accumulation_steps: 2
per_device_eval_batch_size: 1
per_device_train_batch_size: 4

# SFT trainer config
max_steps: -1
num_train_epochs: 5
bf16: true
# do_eval: false
use_liger_kernel: true

data_split: true
# eval_strategy: 'no'
eval_strategy: "steps"
eval_steps: 20
load_best_model_at_end: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: OpenR1-Qwen-3B-SFT
hub_strategy: every_save
log_level: info
logging_steps: 5
logging_strategy: steps
packing: true
output_dir: ckpt_sft/qwen25_3B_sft_with_eval
overwrite_output_dir: true
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 100
seed: 42
train_type: sft
completion_only_loss: true